/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_a3;

import javax.swing.JOptionPane;

/**
 *
 * @author Zucka
 */
public class TelaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form TelaRegistro
     */
    public TelaRegistro() {
        super ("Sistema Acadêmico");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enderecoTextField = new javax.swing.JTextField();
        idadeTextField = new javax.swing.JTextField();
        prioritarioCheckBox = new javax.swing.JCheckBox();
        cadastrarButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        senhaPasswordField = new javax.swing.JPasswordField();
        nomeTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enderecoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite o seu endereço"));

        idadeTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Qual a sua idade"));

        prioritarioCheckBox.setText("Sou acima de 60 anos");
        prioritarioCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prioritarioCheckBoxActionPerformed(evt);
            }
        });

        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        senhaPasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite a sua senha:"));

        nomeTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite o seu nome"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enderecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(prioritarioCheckBox)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(idadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(senhaPasswordField)
                        .addComponent(nomeTextField)))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(senhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prioritarioCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enderecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        TelaLogin dt = new TelaLogin();
        dt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed
    
    public boolean ValidarCampo() {
        String nomeValida = nomeTextField.getText();
        String senhaValida = new String (senhaPasswordField.getPassword());
        int idadeValida = Integer.parseInt(idadeTextField.getText());
        String enderecoValida = enderecoTextField.getText();

        if (nomeValida == null || nomeValida.length() == 0 || senhaValida == null || senhaValida.length() == 0 || idadeValida == 0 || enderecoValida == null || enderecoValida.length() == 0) 
            return false;
        else
            return true;
    }
    
    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
   
    //Recebe dados digitados pelo usuario
    String nome = nomeTextField.getText();
    String senha = new String (senhaPasswordField.getPassword());
    int idade = Integer.parseInt(idadeTextField.getText());
    String endereco = enderecoTextField.getText();
    int prioritario = 0;
    int administrador = 0;
      
    //Lógica checkbox prioritario
    if(prioritarioCheckBox.isSelected()){
        prioritario = 1;
    }else{
        prioritario = 0;
    }
    
    //verifica se o usuário é válido
    try {  
        if(ValidarCampo() == true){
            Usuario usuario = new Usuario(nome,senha,idade,endereco,prioritario,administrador);
            DAO dao = new DAO();
            dao.inserirUsuario(usuario);
            JOptionPane.showMessageDialog(null, "Usuario Cadastrado com sucesso, será redirecionado para a tela de login");
            TelaLogin dt = new TelaLogin();
            dt.setVisible(true);
            this.dispose();
            
        }else{
            JOptionPane.showMessageDialog(null, "Campos invalidados");
        }
        
        
        
        /*if(nome != null){
            if(senha.length() <= 5 ){
                JOptionPane.showMessageDialog(null, "A senha inserida é menor que 5 caracteres");
            }else{
                Usuario usuario = new Usuario(nome,senha,idade,endereco,prioritario,administrador);
                DAO dao = new DAO();
                dao.inserirUsuario(usuario);
                JOptionPane.showMessageDialog(null, "Usuario Cadastrado com sucesso, será redirecionado para a tela de login");
            } 
        }else{
            JOptionPane.showMessageDialog(null, "Alguns dos campos esta vazio, favor preenche-los");
        }
*/        
        
        
    }catch (Exception e){
            JOptionPane.showMessageDialog (null, "Problemas técnicos. Tente novamente mais tarde");
            e.printStackTrace();
        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void prioritarioCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prioritarioCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prioritarioCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JTextField enderecoTextField;
    private javax.swing.JTextField idadeTextField;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JCheckBox prioritarioCheckBox;
    private javax.swing.JPasswordField senhaPasswordField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
